Develop
rightinyourwheelhouse/als-browser pull request #22
Opened 2022-05-25 11:14 UTC by EwoutVerhamme

2022-05-25 12:12 UTC, wardpoel commented on src/components/Dashboard/OnType.jsx
>  			websiteList.forEach((obj) => {
Hier kan gebruik gemaakt worden van een .filter ipv een forEach en dan een externe array te vullen

2022-05-25 12:27 UTC, EwoutVerhamme commented on src/App.jsx
> +				<Route path="/" element={<Dashboard frecency={frecency} />} />
Dit werkt ook, ik had het in de app gezet omdat we er zeker van zijn dat `App` altijd mounted is, dus dat dit ging updaten in de achtergrond.

2022-05-25 12:49 UTC, wardpoel requested changes

2022-05-25 12:49 UTC, wardpoel commented on src/components/Dashboard/OnType.jsx
> +			});
Een .filter geeft je de gefilterde array terug. Geen nood om dus nog een externe array bij te houden. Gewoon zoals je hierboven had staan

2022-05-25 14:06 UTC, EwoutVerhamme commented
De search feature heeft een grote verbetering ondergaan: 
- Indien er van de Google suggestions een link bestaat, zal hij hierbij ook direct de favicon gaan ophalen. 
- Indien de hostname al in je eigen history staat zal hij de google search niet meer tonen => Geen 2 dezelfde websites in je zoekresultaat uit verschillende lijsten

2022-05-27 07:22 UTC, wardpoel approved these changes

2022-05-27 09:35 UTC, merged